### ISSUE TITLE
HPV becomes unresponsive when openHAB is restarted and "Track browser connection" is enabled

### ISSUE THREAD

**Issue by vbier** [vbier/habpanelviewer#19]
Stack trace:
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74d8c8b0 self=0x7faec40a00
  | sysTid=8330 nice=-10 cgrp=default sched=0/0 handle=0x7fb2c81a98
  | state=S schedstat=( 1009239095466 245288473445 3722527 ) utm=77549 stm=23374 core=0 HZ=100
  | stack=0x7fd0c70000-0x7fd0c72000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x04fe4d75> (a io.netty.channel.AbstractChannel$CloseFuture)
  at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:232)
  - locked <0x04fe4d75> (a io.netty.channel.AbstractChannel$CloseFuture)
  at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
  at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
  at io.opensensors.sse.client.impl.netty.EventSourceChannelHandler.close(EventSourceChannelHandler.java:126)
  at io.opensensors.sse.client.EventSource.close(EventSource.java:120)
  - locked <0x095ed10a> (a io.opensensors.sse.client.EventSource)
  at de.vier_bier.habpanelviewer.openhab.ServerConnection.close(ServerConnection.java:240)
  - locked <0x08cc3d7b> (a de.vier_bier.habpanelviewer.openhab.ServerConnection)
  at de.vier_bier.habpanelviewer.openhab.ServerConnection.reconnect(ServerConnection.java:163)
  - locked <0x08cc3d7b> (a de.vier_bier.habpanelviewer.openhab.ServerConnection)
  at de.vier_bier.habpanelviewer.MainActivity$2.disconnected(MainActivity.java:382)
  at de.vier_bier.habpanelviewer.ClientWebView$1.onConsoleMessage(ClientWebView.java:104)
  at com.android.webview.chromium.Ap.onConsoleMessage(WebViewContentsClientAdapter.java:113)
  at org.chromium.android_webview.AwWebContentsDelegateAdapter.addMessageToConsole(AwWebContentsDelegateAdapter.java:50)
  at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native method)

**Comment by vbier** [comment]
Fixed with commit 9b0cd2cb85f8cc49de344a5ed6d774ed606f2ade.
